<div class="modal fade" id="modal-measure">
  <div class="modal-dialog">
    <div class="modal-content">
      <button class="close" id="modal-measure-close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <div class="modal-body">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('modal_measure')->toHtml() ?>
        <!-- <button type="button" class="button-hollow" id="video-modal-trigger" aria-hidden="true">watch video</button> -->
      </div>
    </div> 
  </div> 
</div>

<script type="text/javascript">
//<![CDATA[

    $j( document ).ready(function() {

      if($j("body").hasClass('catalog-product-view')){
        // initModal(mode,delay,modalId,cookieName,interval,bootstrapMode);
        initModal('delay',1000,'#modal-measure','modalmeasure',1,true);
      }

    });    

//]]>
</script>