
<?php if($this->getItems()->getSize()){ ?>

    <?php foreach($this->getItems() as $_item): 

        $img        = $_item->getImage();
        $img_src    = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $img;

        $img_mobile        = $_item->getMobileImage();
        $img_mobile_src    = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $img_mobile;
        
        $link       = $_item->getLink();
    ?>
    <?php endforeach;?>
<?php } ?>


<div class="hero-logo" id="hero-logo"></div>     
<div class="hero-background" style="background-image:url('<?php echo $img_src;?>');"></div> 
<div class="hero-space"></div>


<script type="text/javascript">

/*
$j(document).ready(function(){
    var waypoints = $j('.home-header').waypoint(function(direction) {
                    
    }, {
      offset: '400'
    })
    var waypoints = $j('.home-header').waypoint(function(direction) {
      $j( ".home-header" ).toggleClass('slide-down');
    }, {
      offset: '200'
    })
    var waypoints = $j('.home-header').waypoint(function(direction) {
      $j( "header" ).toggleClass('slide-down');
    }, {
      offset: '-60'
    })
    
})
*/











var Example = (function(){
    
    var settings = {};
    var defaults = {
        maxScroll : 900,
        speed : 5,
        elementScroll : '.page'
    }
    
    // OBJECT OF ANIMATION AND TRANSITIONS RULES
    // MUST BE THIS FORMAT:
    // {
    //    element : 'TRANSITION ELEMENT',
    //    startAt : (INIT OF SCROLL TOP INDEX),
    //    endAt : (END OF SCROLL TOP INDEX),
    //    properties : {    ARRAY OF PROPERTIES
    //        property : {  //THIS IS PROPERTY (EX. x, y, opacity, scale, ETC). MUST BE COMPATIBLE WITH Transit (http://ricostacruz.com/jquery.transit/) SUPORTED PROPERTIES.
    //            start : (START VALUE OF PROPERTY),
    //            end : (END VALUE OF PROPERTY)
    //        }
    //    }
    // }
    var largura = -window.innerWidth;
    var altura = window.innerHeight;
    var animations = [
        
        {
            element : '#hero-logo',
            startAt : 20,
            endAt : 30,
            properties : {
                opacity : { start : 1, end : -1 }
            }
        },
        
    ];
    
    var init = function( param ){
        
        settings = $j.extend( defaults, param );
        
        ScrollAnimator = ScrollAnimator();
        ScrollAnimator.init({
            
            anim : animations,
            maxScroll : defaults.maxScroll,
            speed : defaults.speed,
            elementScroll : defaults.elementScroll
            
        });
        
    }
    
    return {
        init : init
    };
    
})();

$j(document).ready(function(){
    Example.init();
});
</script>
