
<?php if($this->getItems()->getSize()){ ?>

    <?php foreach($this->getItems() as $_item): 

        $img        = $_item->getImage();
        $img_src    = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $img;

        $img_mobile        = $_item->getMobileImage();
        $img_mobile_src    = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $img_mobile;
        
        $link       = $_item->getLink();
    ?>
    <?php endforeach;?>
<?php } ?>


<div class="hero-logo"></div>     
<div class="hero-background" style="background-image:url('<?php echo $img_src;?>');"></div> 
<div class="hero-space"></div>

<div id="element-waypoint">test</div>

<script type="text/javascript">


$j(document).ready(function(){




    var waypoints = $j('#header').waypoint(function(direction) {
      $j( ".hero-logo" ).toggleClass('fade');
      $j( "#header" ).toggleClass('disappear');
    }, {
      offset: '400'
    })

    var sticky = new Waypoint.Sticky({
      element: $j('#header')[0]
    })




})



</script>
