<?php
/*

carousel is invoked in app.js
- css can be found styles.css - look for owl-theme

*/
?>
<?php if($this->getItems()->getSize() > 0): ?>
		<?php foreach($this->getItems() as $data): 
			$_link = $data->getData('link');
			$_image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $data->getData('image');
			$_title 	= $data->getData('title');
			$_desc 		= $data->getData('description');

		?>
            <div class="main">
                <div class="col-main">
                	<div class="caption">
                        <h3><?php echo $_title;?></h3>
                        <p><?php echo $_desc;?></p>
                        <a class="right-arrowed view-now" href="<?php echo $_link;?>">VIEW NOW</a>
                    </div>
                </div>
                <div class="image-right" style="background:url('<?php echo str_replace("\\","/",$_image); ?>') no-repeat center bottom;background-size: auto 105%">
                    <div class="mobile-caption" style="text-align:center;background:#fff">
                        <h3><?php echo $_title;?></h3>
						<a class="right-arrowed view-now" href="<?php echo $_link;?>">VIEW NOW</a>
                    </div>
					<img src="<?php echo str_replace("\\","/",$_image);?>" alt="<?php echo $_title;?>"></a>
                </div>
            </div>
	<?php endforeach;?>
<?php endif; ?>