<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.11
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo $this->__('Blog');?></h1>
    <div class="back-button">
        <button onclick="history.back();" class="button" title="<?php echo $this->__('Back') ?>" type="button">
            <span>
                <span><?php echo $this->__('Back') ?> <i class="fa fa-angle-right"></i></span>
            </span>
        </button>
    </div>
</div>
<div class="postWrapper">
    <div class="blog-image"><?php preg_match_all('/<img[^>]+>/i',$post->getShortContent(), $result); echo is_array($result[0])?$result[0][0]:'' ; ?></div>
    <div class="postTitle">
        <h2><?php echo $post->getTitle(); ?></h2>
        <h3><?php echo date('l, F j, Y',strtotime($post->getCreatedTime())); ?></h3>
    </div>

    <div class="postContent std"><?php echo $post->getPostContent(); ?></div>

    <div class="back-button">
        <button onclick="history.back();" class="button" title="<?php echo $this->__('Back') ?>" type="button">
            <span>
                <span><?php echo $this->__('Back') ?> <i class="fa fa-angle-right"></i></span>
            </span>
        </button>
    </div>

    <!-- social also see below -->
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <div class="addthis_sharing_toolbox"></div>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55428ec0429654f9" async="async"></script>

    <div class="ssi" style="display:none">
        <span class='st_facebook_hcount' displayText='Facebook'></span>
        <span class='st_twitter_hcount' displayText='Tweet'></span>
        <span class='st_googleplus_hcount' displayText='Google +'></span>
        <span class='st_linkedin_hcount' displayText='LinkedIn'></span>
        <span class='st_pinterest_hcount' displayText='Pinterest'></span>
        <span class='st_email_hcount' displayText='Email'></span>
    </div>
    <div class="social-sharing-icons">
        <h3 class="ssi-title">SHARE</h3>
        <span data-icon='st_facebook_hcount'><i class="fa fa-facebook"></i><span class="counter"></span></span>
        <span data-icon='st_twitter_hcount'><i class="fa fa-twitter lighter"></i><span class="counter"></span></span>
        <span data-icon='st_googleplus_hcount'><i class="fa fa-google-plus"></i><span class="counter"></span></span>
        <span data-icon='st_linkedin_hcount'><i class="fa fa-linkedin"></i><span class="counter"></span></span>
        <span data-icon='st_pinterest_hcount'><i class="fa fa-pinterest"></i><span class="counter"></span></span>
        <span data-icon='st_email_hcount' style="width:32px"><i class="fa fa-envelope lighter" style="pointer-events: none;width:32px"></i></span>
    </div>
    <!-- end social -->

</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
    <div class="postTitle"><a name="commentBox" ></a>
        <h2><?php echo $this->__('Post Comments') ?></h2>
    </div>

    <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
        <?php foreach ($comments as $comment) : ?>
            <div class="commentWrapper">
                <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> <?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
            </div>
        <?php endforeach; ?>
     <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>


    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">
                    <div class="fieldset">
                        <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                        <ul class="form-list">
                            <li>

                                <div class="input-box aw-blog-comment-area">
                                    <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <div class="fieldset">
                    <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                            </div>

                            <div class="input-box">
                                <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                            </div>

                            <div class="clear"></div>

                            <div class="input-box aw-blog-comment-area">
                                <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                            </div>
                        </li>

                        <?php
                        if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                            ?><li><?php
                require_once 'recaptcha/recaptchalib-aw.php';

                // Get a key from http://recaptcha.net/api/getkey
                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                $error = null;

                echo recaptcha_get_html($publickey, $error, Mage::app()->getStore()->isCurrentlySecure());
                            ?></li><?php
            }
                        ?>
                    </ul>
                </div>
                <div class="button-set" style="width:96%">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>




<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "d8575cd3-d713-44e6-bb2a-bfbdcec3bb44", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
<script>
// <![CDATA[
var ssi_int = setInterval(function(){
    if($j('.st_facebook_hcount .stBubble_hcount').html()!=undefined && $j('.st_twitter_hcount .stBubble_hcount').html()!=undefined && $j('.st_googleplus_hcount .stBubble_hcount').html()!=undefined && $j('.st_linkedin_hcount .stBubble_hcount').html()!=undefined && $j('.st_pinterest_hcount .stBubble_hcount').html()!=undefined && $j('.st_email_hcount .stBubble_hcount').html()!=undefined){
        if($j('.st_facebook_hcount .stBubble_hcount').html().trim() != "" && $j('.st_twitter_hcount .stBubble_hcount').html().trim() !="" && $j('.st_googleplus_hcount .stBubble_hcount').html().trim() !="" && $j('.st_linkedin_hcount .stBubble_hcount').html().trim() !="" && $j('.st_pinterest_hcount .stBubble_hcount').html().trim() !="" && $j('.st_email_hcount .stBubble_hcount').html().trim() !=""){
            clearInterval(ssi_int);
            $j(".social-sharing-icons").slideDown();
            $j(".social-sharing-icons > span").each(function(){
                var src = $j("."+$j(this).data("icon"));
                if($j(this).data("icon")=="st_email_hcount"){
                    $j(this).append($j("."+$j(this).data("icon")));
                }else{
                    $j(this).find("span.counter").html(src.find(".stBubble_hcount").html());    
                }
            });
            $j(".social-sharing-icons > span").click(function(){
                if($j(this).data("icon")=="st_email_hcount"){
                }else{
                    $j("."+$j(this).data("icon")+" .stButton").trigger("click");    
                }
            });
        }
    }
    
},100);
// ]]>
</script>