<div class="container">
	<div class="page-title">
		<h1>TVHF Tube</h1>
	</div>
</div>
<?php if($this->getItems()->getSize() > 1){ ?>
<div class="std">
	<div class="content video-list">
	<?php 
	$i = 0;
	foreach($this->getItems() as $data): 
		$i++;
		$_video = $data->getData('video');
		$_videoId = $this->getYouTubeIdFromURL($_video);
		$_image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $data->getData('image');
		$_title 	= $data->getData('title');
		$_desc 		= $data->getData('description');
		// optional can use to resize video thumbnail
		$_thumbnail = $this->helper('video/data')->resizeImg($data->getData('thumbnail'),300,360);
	?>
		<div class="section">
			<div class="video-wrap">
		        <?php if($i%2!=0){ ?>
		        <div class="video">
		            <div class="video-wrap">
		            	<a class="video-link" data-toggle="modal" data-target="#video-modal" data-video="<?php echo $_video;?>"><img src="<?php echo $_image;?>" alt="<?php echo $_title;?>"></a>
		            </div>
		        </div>
		        <?php } ?>
				<div class="video-caption">
		            <div class="text-wrap">
	                    <h3><?php echo $_title;?></h3>
	                    <?php echo $_desc;?>
	                    <a class="shop-now video-link" data-toggle="modal" data-target="#video-modal" data-video="">watch now</a>
		            </div>
		        </div>
		        <?php if($i%2==0){ ?>
		        <div class="video">
		            <div class="video-wrap">
		            	<a class="video-link" data-toggle="modal" data-target="#video-modal" data-video="<?php echo $_video;?>"><img src="<?php echo $_image;?>" alt="<?php echo $_title;?>"></a>
		            </div>
		        </div>
		        <?php } ?>
	    	</div>
		</div>
	<?php endforeach;?>
    </div>
</div>


<div class="modal fade" id="video-modal" tabindex="-1" role="dialog" aria-labelledby="video">
<a href="#" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a>            
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="yt-player">
                <div class="embed-container"><iframe src="" frameborder="0" allowfullscreen></iframe></div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php 
// need similar function for Vimeo
function getYouTubeIdFromURL($url) 
{
  $pattern = '%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i';
  preg_match($pattern, $url, $matches);
  return isset($matches[1]) ? $matches[1] : false;
}
?>


<script>
    // load youtube video
    // toto rewrite for vimeo
    // this autoplays when opened
    // and stops when modal closed
    autoPlayYouTubeModal();
    function autoPlayYouTubeModal(){
      var button = $(".video-link");
      button.click(function() {
        var modal = $(this).data( "target" ),
        videoSrc = $(this).attr( "data-video" ), 
        videoSrcAuto = videoSrc+"&amp;autoplay=1" ;
        $j(modal+' iframe').attr('src', videoSrcAuto);
        $j(modal+' .close').click(function () {
            $j(modal+' iframe').attr('src', videoSrc);
        });   
      });
    }
</script>

<?php } ?>